### ISSUE TITLE
+4 card can be played even if i have the running coloured card.

### ISSUE THREAD

**Issue by sagarising** [sharmapr25/UNO#1]
The check on +4 can be played or not is present on the client side and hence, that code can be commented and a player can play +4 card even if he has a the running coloured card.

**Comment by piolAtif** [comment]
This issue has been fixed and has been deployed. Please try and confirm. I will close this issue when you determine that this bug is now fixed.

Thank you.

**Comment by sagarising** [comment]
I appreciate the work you did but still I can throw +4 card even if I have the running coloured card with me. This can be done if the client side javascript's function is altered.

**Comment by sagarising** [comment]
Yeah. Now it works fine.You can close the issue.
Great work!
